site_name: ggml-python
site_url: https://ggml-python.readthedocs.io
repo_url: https://github.com/abetlen/ggml-python

theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.footer

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            group_by_category: false
            signature_crossrefs: true
            show_signature: true
            docstring_section_style: list
            show_root_heading: true
            heading_level: 3
            preload_modules:
              - typing
              - typing_extensions
              - ctypes
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
  - search
  - social

hooks:
  - docs/hooks/jupyterlite.py

markdown_extensions:
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

watch:
  - ggml

nav:
  - "Getting Started": "index.md"
  - "Playground": "playground.md"
  - "API Reference": "api-reference.md"
  - "Changelog": "changelog.md"
