site_name: ggml-python

theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 


watch:
  - ggml