site_name: ggml-python

theme:
    name: readthedocs
    highlightjs: true
    hljs_style: github
    hljs_languages:
        - python

plugins:
    - mkdocstrings:
        handlers:
            python:
                options:
                    members_order: source

watch:
    - ggml